### ISSUE TITLE
Merge "Doctrine Event Listeners and Subscribers" and "Entity Listeners"?

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#10198]
Following up on https://github.com/symfony/symfony-docs/pull/10195

I'm suggesting to merge https://symfony.com/doc/current/bundles/DoctrineBundle/entity-listeners.html and http://symfony.com/doc/current/doctrine/event_listeners_subscribers.html#creating-the-listener-class

Reason: Shouldn't the entity listeners be presented as the preferred way of doing it?
The note that they where introduced in Doctrine 2.4 suggests that they're a brand new feature - however, Doctrine 2.4 was released some 5 years ago ;-)

So since entity listeners have been around for some time, what's the use case for event listeners and subscribers at all anymore?

**Comment by weaverryan** [comment]
I agree! These should certainly live in just one doc. However, two important things:

1) The DoctrineBundle docs (even though they are displayed on symfony.com) are not in our control - they develop those docs separately from us in their repository. For sure we should try to make them work together as much as possible. What we should do first is make our docs how we want them. Then, if there is some duplication, we can propose to remove some things from the bundle.

2) Unrelated to the docs, I believe that the`doctrine.orm.entity_listener` tag is NOT currently autoconfigured. We should really change that in the bundle if possible :)

**Comment by TomasVotruba** [comment]
> @weaverryan Entity listeners do not implement a common interface. That's why they cannot be autoconfigured.

Sure, but why not subscribers that implement `EventSubscriber` interface? 

```yaml
services:
    # why this is not autoconfigured? :(
    Pehapkari\Doctrine\EventSubscriber\SetUploadDestinationOnPostLoadEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber }
```

Now I have to do this manually. It's really WTF while all other common interfaces autoconfigured.
