### ISSUE TITLE
[DI] Add ServiceLocatorArgument to generate array-based locators

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#10335]
It looks like an internal detail, but maybe some text/note/warning mentioned the previous behavior: https://github.com/symfony/symfony/pull/27783

**Comment by ogizanagi** [comment]
This one is actually introducing a new `!service_locator` YAML tag (as well as its counterparts in XML & php-dsl config, which should be documented indeed.
There is no sample in tests, but it should be something like:

```yml
services:
    Foo:
        arguments:
            !service_locator
                my_key_one: '@my_service_one'
                my_key_two: '@my_service_two'
```

XML sample: https://github.com/symfony/symfony/pull/27783/files#r199339505

PHP DSL one should be as simple as:

```php
use Symfony\Component\DependencyInjection\Loader\Configurator\service_locator;
use Symfony\Component\DependencyInjection\Loader\Configurator\ref;

$container->register(Foo::class)->arg('$myLocator', service_locator([
    'my_key_one' => ref('my_service_one'),
    // [...]
]))
