### ISSUE TITLE
[FrameworkBundle] Deprecate auto-injection of the container in AbstractController instances

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#10342]
https://github.com/symfony/symfony/pull/27462

**Comment by javiereguiluz** [comment]
Closing as fixed. We updated all controller examples to always extend from AbstractController and to never show the `$this->get()` shortcut. We even mention explicitly in some articles that you must inject services because controllers extending from AbstractController don't have access to the service container.

**Comment by alegout** [comment]
If your controller is extending AbstractController, not having autowire enabled, and got: 

"User Deprecated: Auto-injection of the container for "App\Controller\DefaultController" is deprecated since Symfony 4.2. Configure it as a service instead."

You need to explicitly inject the container like this:
```
    App\Controller\DefaultController:
        arguments:
            - '@lugosium.inpulsar.webservice.google_cloud.recaptcha'
            - '@monolog.logger'
            - '@lugosium.inpulsar.manager.email'
            - '@translator.default'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - 'controller.service_arguments'
```
