### ISSUE TITLE
[Messenger] Scope handlers per bus & PSR4 discovery

### ISSUE THREAD

**Issue by ogizanagi** [symfony/symfony-docs#10477]
Original PR: https://github.com/symfony/symfony/pull/27275

We should highlight the usage with psr4 discovery for which it works especially great:

```yml
command_handlers:
    namespace: App\Message\
    resource: '%kernel.project_dir%/src/Message/*CommandHandler.php'
    tags:
        - { name: messenger.message_handler, bus: command_bus }

query_handlers:
    namespace: App\Message\
    resource: '%kernel.project_dir%/src/Message/*QueryHandler.php'
    tags:
        - { name: messenger.message_handler, bus: query_bus }
```
