### ISSUE TITLE
Monolog Processors chapter: provided services.yaml not working

### ISSUE THREAD

**Issue by k00ni** [symfony/symfony-docs#10681]
**My setup:**
* PHP 7.2
* Symfony 4.1.7

The chapter about [Monolog Processors](https://symfony.com/doc/current/logging/processors.html) describes a setup which does not seem to work.

I added the `SessionRequestProcessor` file to my project. And adapted the `services.yaml` accordingly. But Symfony ignored it. This is the content of the services.yaml:

```yaml
# config/services.yaml
services:
    monolog.formatter.session_request:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%extra.token%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"

    App\Logger\SessionRequestProcessor:
        tags:
            - { name: monolog.processor }
```

I found another tutorial about processors here: https://nehalist.io/logging-events-to-database-in-symfony/#2addextrainformationbyusingaprocessor

The author used the following `services.yaml`:

```yaml
services:
    monolog.processor.request:
        class: AppBundle\Util\RequestProcessor
        arguments: ['@request_stack', '@service_container']
        tags:
            - { name: monolog.processor, method: processRecord, handler: db }
```

It worked. 

I am very new to the whole monolog thing, so it begs the question if i made a mistake or the documentation should be updated.
