### ISSUE TITLE
[Workflow] How workflows makes sense with DDD

### ISSUE THREAD

**Issue by Nyholm** [symfony/symfony-docs#10819]
More than a handful of times have people asked me how to use the workflow component when doing domain driven design. Im no expert but I think this should be documented and this is how I imagine one solve the problem. 

In DDD the models should know everything about themselves.  Ie the BlogPost entity should have the information about what the places and transitions are. 

```php
namespace App\Entity;

class BlogPost {
  // getters and setters

  public static function getWorkflowDefinition()
  {
        $definitionBuilder = new DefinitionBuilder();
        $definition = $definitionBuilder->addPlaces(['draft', 'published', 'trashed'])
            ->addTransition(new Transition('publish', 'draft', 'published'))
            ->addTransition(new Transition('trash', 'published', 'trashed'))
            ->build();
        return $definition;
  }
}
```

Then we create a generic factory like:
```php
namespace App\Workflow;

use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\Workflow\MarkingStore\MultipleStateMarkingStore;
use Symfony\Component\Workflow\Validator\WorkflowValidator;
use Symfony\Component\Workflow\Workflow;

class WorkflowFactory
{
    private $eventDispatcher;

    public function __construct(EventDispatcherInterface $eventDispatcher)
    {
        $this->eventDispatcher = $eventDispatcher;
    }

    public function create(callable $fetcher, $name)
    {
        $definition = $fetcher();
        (new WorkflowValidator())->validate($definition, $name);
        $marking = new MultipleStateMarkingStore('state');

        return new Workflow($definition, $marking, $this->eventDispatcher, $name);
    }
}
```

Now we can register workflow as services like: 

```yaml
  App\Workflow\WorkflowFactory:
    arguments: ['@event_dispatcher']

  workflow.blog_post:
    class: Symfony\Component\Workflow\Workflow
    factory: ['@App\Workflow\WorkflowFactory', 'create']
    arguments: [['App\Entity\BlogPost', 'getWorkflowDefinition'], 'blog_post']
  
  # Other workflows can use the same factory
  workflow.acme:
    class: Symfony\Component\Workflow\Workflow
    factory: ['@App\Workflow\WorkflowFactory', 'create']
    arguments: [['App\Entity\Acme', 'getWorkflowDefinition'], 'acme']
```
