### ISSUE TITLE
Documentation: How to fix the Command "ContainerAwareCommand" deprecation message.

### ISSUE THREAD

**Issue by greenphp** [symfony/symfony-docs#11053]
I created a Command and have to **access parameters from the service.yml within my Command.** 

At the moment I use **ContainerAwareCommand** in order to have access to `$this->getContainer()->getParameter('my.parameter')` . But this won't work anymore soon, because ContainerAwareCommand is marked as deprecated.

> ContainerAwareCommand class is deprecated, use "Command" with dependency injection instead.

The current documentation https://symfony.com/doc/current/console/commands_as_services.html talks about this deprecated ContainerAwareCommand implementation. 

> In previous Symfony versions, you could make the command class extend from ContainerAwareCommand to get services via $this->getContainer()->get('SERVICE_ID'). This is deprecated in Symfony 4.2 and it won't work in future Symfony versions. 

**Unfortunately it doesn't explain how to access $this->getContainer()->getParameter('my.parameter') in the future nor what to inject into the service.**

Please update the documentation and make it more clear, how to fix this deprecation warning.

**Comment by greenphp** [comment]
Ok, guess, I found the solution to fix it. Nevertheless the documentation could be updated. :)

**service.yml**
```
parameters:
    app.message.welcome: 'Hello Darkness, My Old Friend.'

services: 
    App\Command\MessageCommand:
        tags:
            - { name: 'console.command', command: 'app:message' }
        arguments: ['@service_container']
```

**Command/UpdateCommand.php**
```
use Symfony\Component\Console\Command\Command;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class MessageCommand extends Command
{
    protected static $defaultName = 'app:message';
    protected $container;

    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
	echo $this->container->getParameter('app.message.welcome');
    }

    // ...
}
```
