### ISSUE TITLE
[Validator] Document disable_not_compromised_password option

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony-docs#11327]
Refs : https://github.com/symfony/symfony/pull/30932

Usage:

```yaml
framework:
    validation:
        disable_not_compromised_password: true
```

EUFOSSA
