### ISSUE TITLE
File permission issues still exist in Symfony 4

### ISSUE THREAD

**Issue by bpolaszek** [symfony/symfony-docs#11733]
Current documentation: https://symfony.com/doc/4.3/setup/file_permissions.html

Unfortunately, there are still cases where struggling with ACLs can't be avoided at the core level.

Consider the following setup: 

- I'm user `bob`, I belong to group `www`.
- Application is served through `php-fpm` with user  `www` (group `www`).

I deploy my application as `bob` and run a `bin/console do:something` which writes to the log, here's what the `var/log` directory could look like afterwards:

```bash
-rw-r--r--  1 bob  www   3358 Jun 12 17:12 prod.deprecations.log
-rw-r--r--  1 bob  www  33779 Jun 12 17:11 prod.log
```
Some time later, a user reaches `https://my.app/writeSomethingInTheLogs` => boom, user `www` can't write in the existing `prod.log`.

The inverted scenario of "`bob` could not launch a command because `www` already touched the log file" can also exist.

Thus, I think this should be documented since it can break production at an unpredictable moment.

Possible solutions are:

- Same user for cli / www (with the associated warns about security concerns)
- `chmod +a` when possible (AFAIK, almost never)
- `setfacl` on Linux (I personnally didn't manage to make it work on FreeBSD)
- `umask`, but the setting is per-process (and a FPM process may handle multiple requests)
- Explicitely configuring the `monolog` package as follows:

```yaml
# config/packages/monolog.yaml
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            file_permission: 0664
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            file_permission: 0664
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
```

Apart from the documentation, I also wonder if we should set `0666` as default file permissions for the logs?

What are your thoughts?

Related: #10946
