### ISSUE TITLE
Description of EnvelopeListener not matching my result

### ISSUE THREAD

**Issue by auipga** [symfony/symfony-docs#11836]
> ..., you might want to always send emails to a specific address, **instead** of the real address
in https://github.com/symfony/symfony-docs/blob/master/mailer.rst

EnvelopeListener overrides `bcc`, not `to`. Either docs or code is wrong.
```yaml
services:
    mailer.dev.set_recipients:
        class: Symfony\Component\Mailer\EventListener\EnvelopeListener
        tags: ['kernel.event_subscriber']
        arguments:
            $sender: null
            $recipients: ['example+envelop@gmail.com']
```
```php
$email = (new TemplatedEmail())
    ->to('example+TO@gmail.com')
    ->cc('example+CC@gmail.com')
    ->bcc('example+BCC@gmail.com')
    ->replyTo('example+REPLY-TO@gmail.com')
```
![Screenshot from 2019-06-27 13-19-13](https://user-images.githubusercontent.com/876689/60262450-7a16ff80-98de-11e9-8b06-9310812352c1.png)
