### ISSUE TITLE
[Messenger] Change doctrine middleware order 

### ISSUE THREAD

**Issue by wtorsi** [symfony/symfony-docs#11868]
Please, change doctrine middleware order in docs [https://symfony.com/doc/current/messenger.html#middleware-for-doctrine](https://symfony.com/doc/current/messenger.html#middleware-for-doctrine) 
The valid order for full stack of doctrine middleware is: (also, please include default_bus option)
```yaml
framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_transaction
```
