### ISSUE TITLE
[Messenger] Prioritized Transports example does not work

### ISSUE THREAD

**Issue by ghost** [symfony/symfony-docs#11967]
For the Prioritized Transports, the example displayed does not work. I solved it in my code using two different dsn (not sure it is the best pratice).
In the doc, we have :
```yaml
#.env
MESSENGER_TRANSPORT_DSN=amqp://guest:guest@localhost:5672/%2f/messages

#config/packages/messenger.yaml
framework:
    messenger:
        transports:
            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    # queue_name is specific to the doctrine transport
                    # try "exchange" for amqp or "group1" for redis
                    queue_name: high
            async_priority_low:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: low

        routing:
            'App\Message\SmsNotification':  async_priority_low
            'App\Message\NewUserWelcomeEmail':  async_priority_high
```

It should be :
```yaml
#.env
MESSENGER_TRANSPORT_DSN_HIGH=amqp://guest:guest@localhost:5672/%2f/messages_high
MESSENGER_TRANSPORT_DSN_LOW=amqp://guest:guest@localhost:5672/%2f/messages_low

#config/packages/messenger.yaml
framework:
    messenger:
        transports:
            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_HIGH)%'
                options:
                    # queue_name is specific to the doctrine transport
                    # try "exchange" for amqp or "group1" for redis
                    queue_name: high
            async_priority_low:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_LOW)%'
                options:
                    queue_name: low

        routing:
            'App\Message\SmsNotification':  async_priority_low
            'App\Message\NewUserWelcomeEmail':  async_priority_high
```

**Comment by weaverryan** [comment]
The problem is that the docs assume you're using the `doctrine` transport - and the `queue_name` is specific to the doctrine transport. If you look at the docs - https://symfony.com/doc/current/messenger.html#prioritized-transports - there is a comment that says:

> # queue_name is specific to the doctrine transport
> # try "exchange" for amqp or "group1" for redis

Does that help? I think just changing `queue_name` to `exchange` would work for amqp - can you confirm?

Side note - we need to add "option" validation to the transport. The amqp transport should (in a perfect world) throw an exception if this non-existent queue_name option is passed to it.

**Comment by OlivierFromLille** [comment]
Hi @weaverryan, Thanks for your answer.

With amqp, according to the doc, we should have this :
```
#.env
MESSENGER_TRANSPORT_DSN=amqp://guest:guest@localhost:5672/%2f/messages

#config/packages/messenger.yaml
framework:
    messenger:
        transports:
            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: 'high'
            async_priority_low:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: 'low'

        routing:
            'App\Message\SmsNotification':  async_priority_low
            'App\Message\NewUserWelcomeEmail':  async_priority_high
```

But if I launch this command : sf messenger:consume async_priority_high -vvv
all messages from both transports will be handled.

In Symfony\Component\Messenger\Transport\AmqpExt\Connection, in the function fromDsn(...), we can see 2 options named 'exchange' and 'queues' :
```
$exchangeOptions = $amqpOptions['exchange'];
$queuesOptions = $amqpOptions['queues'];
```
Maybe I should set something for queue option but I don't know what :(

That's the reason why I created 2 variables, MESSENGER_TRANSPORT_DSN_HIGH and MESSENGER_TRANSPORT_DSN_LOW to bypass the problem.
