### ISSUE TITLE
[Validation][FrameworkBundle] Add auto_mapping config

### ISSUE THREAD

**Issue by ogizanagi** [symfony/symfony-docs#12728]
I may have missed it, but I didn't find any documentation about the `validation.auto_mapping` config in FrameworkBundle (nor in the fwb ref page).

Ex:

```yml
framework:
    validation: 
        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        auto_mapping:
            App\Entity\: []
```

(ref https://github.com/symfony/recipes/pull/664)

**Comment by carsonbot** [comment]
Thank you for this issue.
There has not been a lot of activity here for a while. Has this been resolved?

**Comment by carsonbot** [comment]
Hello? This issue is about to be closed if nobody replies.

**Comment by ogizanagi** [comment]
This feature still isn't documented

**Comment by ro0NL** [comment]
@ogizanagi can you tell me if an an empty array is intended to disable auto-validation, or could it mean validate everything actually? We got this issue https://github.com/symfony/symfony/issues/44693 :D

**Comment by ogizanagi** [comment]
An empty array where? IIRC:

```yaml
framework:
    validation:
        auto_mapping:
            App\Entity\: []
```
should auto-validate everything in the `App\Entity\` ns.

```yaml
framework:
    validation:
        auto_mapping: []
```
should not enable auto-validation in any ns.
