### ISSUE TITLE
Missing hint that setting cache-limiter as defined in the docs resets all session configuration

### ISSUE THREAD

**Issue by codegain** [symfony/symfony-docs#12747]
At https://symfony.com/doc/4.3/reference/configuration/framework.html#cache-limiter there should be some hint saying that setting

```
# config/services.yaml
parameters:
    session.storage.options:
        cache_limiter: 0
```

resets session parameters like "cookie_samesite", "cookie_secure" and "cookie_httponly" to their default value.

**Comment by javiereguiluz** [comment]
In the related Pull Request which was closed, some more info was provided: https://github.com/symfony/symfony-docs/pull/13518

```
@nicolas-grekas I was working on a project were these settings were set in framework.yaml:

session:
    storage_id: 'session.storage.native'
    name: 'PHPSESSID'
    cookie_samesite: 'lax'
    cookie_secure: true
I set cache_limiter to nocache (via the container parameter as described in the docs). However, some days later I discovered that the samesite and https attributes of my session cookies disappeared. After I deleted the cache_limiter container parameter and re-logged into my application, the attributes appeared again.

I think the session.storage.options parameter somehow overrides all or some session config from framework.yaml. Unfortunately I didn't have enough time to look further into it.

EDIT: I forgot to mention that I also checked phpinfo(); which showed me that with session.storage.options set, all session values returned to their default value from the php.ini (except cache_limiter). After I removed it, the settings were set back to what was set in the framework.yaml config.
```

However, we aren't 100% sure about this yet ... so we need to investigate further before making any changes. Thanks!

**Comment by codegain** [comment]
@javiereguiluz If you need someone to look into this, I could test this again with 4.4 and see if anything changed

**Comment by codegain** [comment]
I did a small test on my application and this is still happening as of Symfony 4.4.18 running on PHP 7.4.12.

framework.yaml:
```
framework:
    session:
        enabled: true
        handler_id: 'session.handler.native_file'
        save_path: '/tmp/sessions'
        name: 'SYMFONYSESSID'
        use_cookies: true
        cookie_lifetime: 300
        cookie_secure: true
        cookie_httponly: true
        cookie_samesite: 'lax'
```

![before-nocache](https://user-images.githubusercontent.com/11192306/102902996-040e3d00-4470-11eb-8684-b7632540f327.png)

The values are correctly set. If I add

```
parameters:
    session.storage.options:
        cache_limiter: 'nocache'
```

to my services.yaml, this happens:

![after-nocache](https://user-images.githubusercontent.com/11192306/102903145-35870880-4470-11eb-94c8-65045f449ca2.png)

`session.cache_limiter` is now set to `nocache` (as configured), but the following settings will not be set:

- session.cookie_httponline (should be 1, now "no value")
- session.cookie_lifetime (should be 300, now 0)
- session.cookie_samesite (should be "lax", now "no value")
- session.cookie_secure (should be 1, now 0)
- session.name (should be "SYMFONYSESSID", now "PHPSESSID")
