### ISSUE TITLE
TemplateController: extra arguments passed to the template are not managed by Symfony

### ISSUE THREAD

**Issue by Rebolon** [symfony/symfony-docs#12897]
Playing with TemplateController, i saw in the documentation https://symfony.com/doc/master/templates.html#rendering-a-template-directly-from-a-route that i may send extra arguments

In fact, those extra arguments seems not managed by the TemplateController following the source code https://github.com/symfony/symfony/blob/5.0/src/Symfony/Bundle/FrameworkBundle/Controller/TemplateController.php (same for 4.*)

Maybe the documentation is not enough explicit about what those extra arguments are used byt Symfony, if they are.

**Comment by yceruto** [comment]
You're right, this part is not currently supported:
```yaml
# optionally you can define some arguments passed to the template
site_name: 'ACME'
theme: 'dark'
```
but it looks like a good feature to me :)
