### ISSUE TITLE
[FrameworkBundle] Configure RequestContext through router config

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#12913]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#35281
| PR author(s) | @benji07
| Merged in    | 5.1-dev

**Comment by javiereguiluz** [comment]
In the docs (see https://symfony.com/doc/current/routing.html#generating-urls-in-commands) we currently explain the request context config in two ways: (1) container parameters and (2) `$this->router->getContext()` methods.

I was going to replace (1) wit this new config ... because we can't explain the same thing in 3 different ways ... but there's a problem.

We have the `router.request_context.*` params and the `asset.request_context.*` params. So, if I remove the first params to use the new config ... I must keep the "asset" param because it's not supported in the new config.

@symfony/team-symfony-docs What should we do here? Thanks!

**Comment by xabbuh** [comment]
I would change

```yaml
# config/services.yaml
parameters:
    router.request_context.host: 'example.org'
    router.request_context.base_url: 'my/path'
    asset.request_context.base_path: '%router.request_context.base_url%'
```

to

```yaml
# config/services.yaml
parameters:
    asset.request_context.base_path: '%router.request_context.base_url%'

# config/packages/routing.yaml
framework:
    router:
        context:
        host: 'example.org'
        base_url: 'my/path'
```
