### ISSUE TITLE
[FrameworkBundle] TemplateController should accept extra arguments to b…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#12929]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#35257
| PR author(s) | @Benjamin RICHARD
| Merged in    | 5.1-dev

**Comment by yceruto** [comment]
We need to update the doc to:
```yaml
    # ...
    # optionally you can define some arguments passed to the template
    context: 
        site_name: 'ACME'
        theme: 'dark'
```
