### ISSUE TITLE
Default installation - missing step

### ISSUE THREAD

**Issue by AleksejJur** [symfony/symfony-docs#13176]
Following default installation https://symfony.com/doc/current/security.html, there is missed step

1) Installation - ok 
2a) Create your User Class - after we create User entity, security.yaml is updated, but we can't run  php bin/console make:migration because, in security.yaml 

```
providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: users_in_memory
```

In firewalls -> main -> provider = users_in_memory
But provider is - app_user_provider

So we need to change one of them to match
