### ISSUE TITLE
wrong versions for DoctrineMigrationsBundle documentation

### ISSUE THREAD

**Issue by goetas** [symfony/symfony-docs#13375]
Currently the documentation points to the un-released master branch (3.0), marking it as 2.0.

https://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html

I'm not familiar on how the documentation is generated here, how can I help?

**Comment by javiereguiluz** [comment]
This is the current config we have for this bundle in the private symfony.com repo:

```yaml
doctrine-migrations-bundle:
    branches: ["1.3", "master"]
    maintained_branches: ["1.3", "master"]
    master_alias: "2.0"
```

I don't know this bundle well, so please, tell me which changes would be necessary. Thanks!

**Comment by goetas** [comment]
The right configs should be:

```yml
doctrine-migrations-bundle
    branches: ["1.8", "2.3.x", "master"]
    maintained_branches: ["1.8", "2.3.x", "master"]
    master_alias: "master"
```

This will change soon. Is there a way to not display for now "master" ? (as is a large WIP and BC break.

Are this config public in some repo?

**Comment by javiereguiluz** [comment]
`master_alias` can't be `master` 😓  It must be the version number of the next stable version. It can be `3.x` for example instead of a specific number such as `3.0`.

We cannot not display "master" ... and don't worry for being WIP ... it happens the same in most bundles.

I'm afraid that this config is not in a public repository. Sorry!

**Comment by goetas** [comment]
I see. Thanks for the info!

Can you set this config then?
```yml
doctrine-migrations-bundle:
    branches: ["1.8", "2.3.x", "master"]
    maintained_branches: ["1.8", "2.3.x", "master"]
    master_alias: "3.0"
```
