### ISSUE TITLE
[Routing] Sub-domain routing hostname

### ISSUE THREAD

**Issue by enumag** [symfony/symfony-docs#13419]
The [sub-domain routing](https://symfony.com/doc/current/routing.html#sub-domain-routing) documentation is currently missing a vital piece of information:

How to avoid having the domain name (example.com) in the Route annotations? I need to be able to deploy my application to different domains so of course I can't have it there like this. I need to configure it using an ENV variable or something like that or simply let it be anything - controller doesn't care which domain is the application running on.

Can you please tell me how to do it? I can send a PR for the documentation once I know the solution.

Thanks.

**Comment by dbrumann** [comment]
There are many solutions to this problem. Maybe you can head over to Stack Overflow and explain your exact use case to get the best option for your scenario.

Generally speaking you can have multiple dynamic parts, e.g. something like:

```
index:
    path: /
    host: '{subdomain}.{host}.com'
    controller: App\Controller\DefaultController::index
    requirements:
        subdomain: 'm|mobile|www'
    defaults:
        host: 'example'
```

This will allow you to switch between different subdomains and hosts where subdomains are restricted to "m.", "mobile." and "www." but hosts are completely unrestricted (other than not having a "." in there). You could also add `{tld}` to switch between different TLDs like ".com", ".org" or ".net". By default each segment uses the pattern `[^\.]+`, so one or more characters that are not "." for tld you will have to change this, e.g. to ".+" (or better a list with explicitly allowed tlds) to allow something like "co.uk".

If you just want to have flexible host and subdomain but with fixed TLD you can also modify the regex in the requirements to your needs, e.g. have something like this:

```
index:
    path: /
    host: '{host}.{tld}'
    controller: App\Controller\DefaultController::index
    requirements:
      host: '([^\.]+\.)?[^\.]+'
      tld: 'com|org|co\.uk'
    defaults:
        host: 'example'
        tld: 'com'
```

This will allow multiple combinations like "example.com", "foo.example.com", but not "foo.bar.example.com" or "example.net".

I agree the docs could use some improvement to highlight that you can use more advanced regex patterns for flexible host matching. I would love to see a PR from you. 🙂
