### ISSUE TITLE
[FrameworkBundle] Deprecate flashbag and attributebag services

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13467]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#36273
| PR author(s) | @William Arslett
| Merged in    | 5.1-dev

**Comment by javiereguiluz** [comment]
@warslett I've found a single occurrence of these deprecated services in the Symfony Docs. It's this example about "namespaced session attributes":

```yaml
.. code-block:: yaml

    # config/services.yaml
    session:
        public: true
        class: Symfony\Component\HttpFoundation\Session\Session
        arguments: ['@session.storage', '@session.namespacedattributebag', '@session.flash_bag']

    session.namespacedattributebag:
        class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
```

How could we remove the `'@session.flash_bag'` service in this config? Thanks.

**Comment by warslett** [comment]
@javiereguiluz I will test this to be sure but in theory you don't need to inject a flashbag. If you want to use the default flashbag, you just set the flashbag parameter to null. The deprecated flashbag service uses service as a factory so it will always be the flashbag contained in the service. I'd suggest this as the recommended approach for injecting NamespacedAttributeBag:

```
# config/services.yaml
    session:
        public: true
        class: Symfony\Component\HttpFoundation\Session\Session
        arguments: ['@session.storage', '@session.namespacedattributebag', ~]

    session.namespacedattributebag:
        class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
```

**Comment by warslett** [comment]
or even just:
```
# config/services.yaml
    session:
        public: true
        class: Symfony\Component\HttpFoundation\Session\Session
        arguments: ['@session.storage', '@session.namespacedattributebag']

    session.namespacedattributebag:
        class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
```
