### ISSUE TITLE
Accept Self signed certificate in HttpClient

### ISSUE THREAD

**Issue by louia** [symfony/symfony-docs#13763]
**Description**  

Allow user to use self signed certificate in HttpClient. 
For CurlHttpClient : use : 
`  curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);`

**Example**  

        $client = new CurlHttpClient();
        $client->AllowSelfSignedCertificate();

**Comment by javiereguiluz** [comment]
@louia thanks for reporting this problem. I've moved your issue to the `symfony-docs` repository so we can take care of it.

**Comment by javiereguiluz** [comment]
Closing as fixed because both `verify_peer` and `verify_host` options have been added to the HttpClient config reference: https://symfony.com/doc/current/reference/configuration/framework.html#reference-http-client

**Comment by gitMomo** [comment]
Hello everyone,

I'm using symfony 5.1 and trying to disable the ssl verification by using verify_peer & verify_host  in dev env :

```
// config/packages/dev/http_client.yaml
framework:
  http_client:
    default_options:
      verify_peer: false
      verify_host: false
```
      
When i dump my current http_client config i see that they are disabled :

```
❯ php bin/console debug:config framework http_client
Current configuration for "framework.http_client"
=================================================
default_options:
    verify_peer: false
    verify_host: false
    headers: {  }
    resolve: {  }
enabled: true
scoped_clients: {  }
```

But they are still enabled when i dump my client object :

```
Symfony\Component\HttpClient\CurlHttpClient {#9
  -defaultOptions: array:31 [
    //...
    "bindto" => "0"
    "verify_peer" => true
    "verify_host" => true
    "cafile" => null
    //...
  ]
  -multi: Symfony\Component\HttpClient\Internal\CurlClientState {#39 …}
  #logger: Symfony\Bridge\Monolog\Logger {#70 …6}
}
```
