### ISSUE TITLE
[Mailer] Document `envelope:sender` configuration

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#13863]
https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L1506 shows that there is a `sender` key like this:

```yaml
# config/packages/mailer.yaml
framework:
    mailer:
        envelope:
            sender: 'foobar'
```

This should be documented at https://symfony.com/doc/master/mailer.html
