### ISSUE TITLE
[Lock] Configure lock component via framework-bundle with a DBAL Connection 

### ISSUE THREAD

**Issue by rvitaliy** [symfony/symfony-docs#14009]
Hi all.
i want to configure lock  using mysql and current DBAL connection. But i cant understand how to configure it.
refs:
https://symfony.com/doc/current/components/lock.html#pdostore
https://symfony.com/doc/current/reference/configuration/framework.html#lock
manually is likes:
```yaml
    Symfony\Component\Lock\Store\PdoStore:
        arguments:
            $connOrDsn: '@doctrine.dbal.default_connection'

    Symfony\Component\Lock\LockFactory:
        arguments:
            $store: '@Symfony\Component\Lock\Store\PdoStore'
```

Thanks!
