### ISSUE TITLE
[Messenger] some doctrine transport options are not documented

### ISSUE THREAD

**Issue by Nek-** [symfony/symfony-docs#14221]
Options of the postgresql transport are not documented:
- check_delayed_interval
- get_notify_timeout

And the check_delayed_interval is important since this PR: https://github.com/symfony/symfony/pull/36990 because it adds a delay of 1min before starting to process messages by default. We run into this "issue" and had hard times figuring out why it was like that.

I assume it should be documented somewhere in the middle of this:
https://symfony.com/doc/current/messenger.html#doctrine-transport

And since this issue may save lives, here is the configuration that makes it work like in Sf 5.0!

```yaml
framework:
    messenger:
        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    check_delayed_interval: 1000
```
