### ISSUE TITLE
[Messenger] Type-hints and auto-wiring wrongly states that a manual binding is required if using multiple buses

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony-docs#14382]
Starting from SF4.2, autowiring works out of the box, creating automatically the bindings with the names of the configured buses.

So, this is not required anymore:

```yaml
# config/services.yaml
services:
    _defaults:
        # ...

        bind:
            $commandBus: '@messenger.bus.commands'
            $queryBus: '@messenger.bus.queries'
            $eventBus: '@messenger.bus.events'
```

Source: https://symfony.com/doc/4.2/messenger/multiple_buses.html#type-hints-and-auto-wiring

Here we should say that it is sufficient to do something like this:

```php
public function __construct(MessageBusInterface $myNewBus)
```

It well explained also on SymfonyCasts: https://symfonycasts.com/screencast/messenger/event-bus#creating-a-second-bus

**Comment by Nyholm** [comment]
It does, doesn't it?

Check the docs for master: https://symfony.com/doc/master/messenger/multiple_buses.html

```
This will create three new services:

- command.bus: autowireable with the Symfony\Component\Messenger\MessageBusInterface type-hint (because this is the default_bus);
- query.bus: autowireable with MessageBusInterface $queryBus;
- event.bus: autowireable with MessageBusInterface $eventBus.
```

**Comment by Aerendir** [comment]
@Nyholm , I'm referring to the version 4.2 of the documentation: shouldn't it say the same thing said starting from the version 4.3?

It seems to me that the feature was added in version 4.2, but that it is reported in documentation only from version 4.3.

**Comment by Aerendir** [comment]
To be clearer:

v4.2 (https://symfony.com/doc/4.2/messenger/multiple_buses.html#type-hints-and-auto-wiring)

```yaml
# config/services.yaml
services:
    _defaults:
        # ...

        bind:
            $commandBus: '@messenger.bus.commands'
            $queryBus: '@messenger.bus.queries'
            $eventBus: '@messenger.bus.events'
```

v4.3 (https://symfony.com/doc/4.3/messenger/multiple_buses.html)

> This will create three new services:
>
> - command.bus: autowireable with the Symfony\Component\Messenger\MessageBusInterface type-hint (because this is the >default_bus);
> - query.bus: autowireable with MessageBusInterface $queryBus;
> - event.bus: autowireable with MessageBusInterface $eventBus.
