### ISSUE TITLE
[Documentation Website] Section titles are hidden behind header bars

### ISSUE THREAD

**Issue by Tom32i** [symfony/symfony-docs#14635]
When clicking on an anchor on the current ducomentation website, the section's title is hidden behind the header bars:

| Current behavior | Fixed Behavior |
| --- | --- | 
| ![current](https://user-images.githubusercontent.com/1846873/100588798-92b8ef80-32f2-11eb-9db4-326e88185c2c.png) | ![fixed](https://user-images.githubusercontent.com/1846873/100588790-90ef2c00-32f2-11eb-87c7-c8bccbe4f08e.png) | 

This could be prevented by using the [scroll-margin-top](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-top) CSS property on elements targeted by the anchors:

```css
.section {
    scroll-margin-top: 96px; /* 40px (sln bar)  + 36px (navigation bar) + 20px (a little margin) */
}
```

Note: the scrolling already behave as expected on _page load_ but not when using an anchor link, like in the table of contents at the top of the page for example.

Note 2: I couldn't find the CSS style for the documentation website in this repository, otherwise I would have directly submit a pull request.
