### ISSUE TITLE
[Cache] Redis Adapter wrongly purpose a compression option

### ISSUE THREAD

**Issue by bastnic** [symfony/symfony-docs#15050]
Since https://github.com/symfony/symfony/pull/34133, the `compression` is gone but it's still documented here https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html#available-options and marked as enabled by default.

I'm still trying to figure if my app lost the compression by upgrading to 4.4 / 5.x.

**Comment by Nyholm** [comment]
Thank you for this issue. 

The `compression` option was never released in 4.4. It did not work and was removed. 

> I'm still trying to figure if my app lost the compression by upgrading to 4.4 / 5.x.

No, but it may have lost compression upgrading from 4.3 to 4.4. 

Also note that this is a "Redis cache" and not a "Redis store". A cache can always be calculated and will never store something valuable.

**Comment by bastnic** [comment]
Hi @Nyholm, 

I upgraded my app 4.1 => 4.2 => 4.3 => 4.4 => 5.0 => 5.1. So in a certain time I had the compression working then not. I've issue with high redis bandwidth right now. I assumed I had a compression knowing the parameter and having redis correctly installed. But I saw that the cached value was plain php serialized data, no binary. I unrolled everything and voila.

**Comment by Nyholm** [comment]
Interesting. Will the `DeflateMarshaller` help you?

```
services:
    Symfony\Component\Cache\Marshaller\DeflateMarshaller:
        decorates: cache.default_marshaller
        arguments: ['@Symfony\Component\Cache\Marshaller\DeflateMarshaller.inner']
```
