### ISSUE TITLE
[doctrine] Documentation about subscribers is outdated

### ISSUE THREAD

**Issue by Nek-** [symfony/symfony-docs#15234]
[The documentation about doctrine](https://symfony.com/doc/current/doctrine/events.html#doctrine-lifecycle-subscribers) state things about subscribers but it's not up to date because the situation changed in the doctrine bundle.

### Before:

```php
class MyAwesomeSubscriber implements EventSubscriber
{
    // ...
}
```

```yaml
# config/services.yaml
services:
    # ...

    App\Doctrine\MyAwesomeSubscriber:
        tags:
            - { name: 'doctrine.event_subscriber' }
```

### After:

```php
class MyAwesomeSubscriber implements EventSubscriberInterface
{
    // ...
}
```

_(and that's all)_

Changed since Doctrine Bundle 2.1.0.
