### ISSUE TITLE
Proposed fix to avoid hide of anchor links behind sticky menu

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony-docs#15432]
When I'm link for example to: https://symfony.com/doc/current/reference/forms/types/form.html#inherit-data

The `#inherit-data` headline is hidden between the sticky header.

By adding the following to the `CSS` should avoid this problem :

```css
html {
    scroll-padding-top: 90px;
}
```
