### ISSUE TITLE
Defining Multiple Webpack Configurations docs might be missing a step

### ISSUE THREAD

**Issue by iampedropiedade** [symfony/symfony-docs#15540]
I think documentation is missing a step on the assets.yaml to define the multiple manifest.json files:

https://symfony.com/doc/current/frontend/encore/advanced-config.html

```
framework:
    assets:
        packages:
            app:
                json_manifest_path: '%kernel.project_dir%/public/build/app/manifest.json'
            dashboard:
                json_manifest_path: '%kernel.project_dir%/public/build/dashboard/manifest.json'
```

instead of the original:

```
framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
```

https://github.com/symfony/symfony-docs/pull/15539
