### ISSUE TITLE
enable_authenticator_manager option placement in security.yaml

### ISSUE THREAD

**Issue by sukhoy94** [symfony/symfony-docs#16122]
Hi, I have recognized some unclear behavior of enable_authenticator_manager option in security.yaml.
If I have defined some custom authenticators for my firewall. `enable_authenticator_manager: true` cannot be declared before that firewall. If it is, my custom authenticator seems like not running. I think it should by mentioned in documentation.

```
enable_authenticator_manager: true
custom_firewall: 
            pattern: ^/customfirewall
            provider: jwt
            jwt:
                authenticator: app.custom_authenticator
```

Anyway for me it's totally unclear what does that option designed for. There is a link there in documentation (https://symfony.com/doc/current/security.html), but seems like it's provide to nowhere.

```
security:
    # https://symfony.com/doc/current/security/experimental_authenticators.html
    enable_authenticator_manager: true
```
