### ISSUE TITLE
The documented "command_bus" doesn't work

### ISSUE THREAD

**Issue by LinkingYou** [symfony/symfony-docs#16422]
On https://symfony.com/doc/5.4/messenger.html#other-middlewares is descriped how to configure "router_context" middleware:

```
framework:
    messenger:
        buses:
            command_bus:
                middleware:
                    - router_context
                    - validation
```

This is not working for me. If i rename "**command_bus**" to "**command.bus**" all works as expected:

```
framework:
    messenger:
        buses:
            command.bus:
                middleware:
                    - router_context
                    - validation
```

The "command_bus" is used multiple times on this page.
