### ISSUE TITLE
[Security] Firewall Logout configuration missing `delete_cookies`

### ISSUE THREAD

**Issue by mbabker** [symfony/symfony-docs#16477]
I was giving feedback on an issue in another bundle about making sure certain cookies are cleared on logout and found that the `delete_cookies` key isn't documented.

Prototype from the `bin/console config:dump-reference security` output:

```yaml
security:
    firewalls:            # Required
        # Prototype
        name:
            logout:
                delete_cookies:

                    # Prototype
                    name:
                        path:                 null
                        domain:               null
                        secure:               false
                        samesite:             null
```
