### ISSUE TITLE
"Create your First Page in Symfony" instructions don't work using Symfony Docker

### ISSUE THREAD

**Issue by linkedupbits** [symfony/symfony-docs#18405]
I am trying to follow the "hello world" example at https://symfony.com/doc/current/page_creation.html#creating-a-page-route-and-controller using a docker image, and it doesn't work - when I view the page in the browser I get:

> The controller for URI "/lucky/number" is not callable: Controller "App\Controller\LuckyController" cannot be fetched from the container because it is private. Did you forget to tag the service with "controller.service_arguments"?

I have:
 - cloned https://github.com/dunglas/symfony-docker
 - build the images and started the containers
 - added a new file src/Controller/LuckyController.php (with contents as per the example)
 - edited the existing config/routes.yaml
 - tried browsing the page

Is there something obvious I am missing?

I have also tried the [annotations](https://symfony.com/doc/current/page_creation.html#annotation-routes) and that has errors with the route not working.

**Comment by maxhelias** [comment]
I think you're missing the `#[AsController]` in your class and even in the documentation 😅

**Comment by alexandre-daubois** [comment]
I just tried and wasn't able to reproduce. Could you maybe link a repo so we're able to test your reproducer and be sure we have the same code?

**Comment by linkedupbits** [comment]
steps to reproduce:

delete all images and containers in docker desktop for good measure...

Terminal 1:
``` bash

git clone https://github.com/dunglas/symfony-docker
cd symfony-docker
docker compose build --pull --no-cache
docker compose up
```

Terminal 2:
``` bash
docker exec -it symfony-docker-php-1 /bin/sh
apk add vim
vim /srv/app/src/Controller/LuckyController.php
vim /srv/app/config/routes.yaml 
```

src/Controller/LuckyController.php
``` php
// src/Controller/LuckyController.php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;

class LuckyController
{
    public function number(): Response
    {
        $number = random_int(0, 100);

        return new Response(
            '<html><body>Lucky number: '.$number.'</body></html>'
        );
    }
}
```

src/config/route.yaml
``` yaml
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
```
