### ISSUE TITLE
Confusing example of the console monolog handler

### ISSUE THREAD

**Issue by speller** [symfony/symfony-docs#20700]
The page https://symfony.com/doc/current/logging/monolog_console.html suggests the following `console` handler:

```yaml
# config/packages/dev/monolog.yaml
monolog:
    handlers:
        # ...
        console:
            type:   console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
```

At the same time, it excludes the `console` channel by having the `!console` exclusion config value. How does it work if it doesn't accept messages from the `console` channel?

**Comment by 94noni** [comment]
hum as far as I get it, the `console` handler and the `console` channel are not defacto linked
you can totally decide to have a `console` and to exclude all logs from the `console` channel
(but I get you that the confusion can be here)

**Comment by javiereguiluz** [comment]
Closed by #21891.

**Comment by speller** [comment]
@javiereguiluz @lacatoire 
Thank you guys for improving the docs and working on the issue that I created!

At the same time, while I use Symfony for a lot of time already, I'm still confused even with the added explanation. 

```yaml
# config/packages/dev/monolog.yaml
monolog:
    handlers:
        # ...
        console:
            type:   console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
```

The main question: WHY do we name the handler `console`, set its type as `console`, and exclude the `console` events? I would expect some additional clarification like this: in this example, we create a handler named "console", configure it with "type: console" to ...<add knowledge here, why meand type console>... and exclude events from the following channels: from event dispatcher ("!event"), from doctrine ("!doctrine"), and ....<add knowledge here, what are the event from this channel>.... I think all readers would greatly appreciate this kind of addition.
