### ISSUE TITLE
Removing AcmeDemoBundle related sections from security.yml

### ISSUE THREAD

**Issue by zomberg** [symfony/symfony-docs#5080]
http://symfony.com/doc/current/cookbook/bundles/remove.html

I was started with fresh Symfony 2.6.4 instalation and removed AcmeDemoBundle

But for security.yml file documentation looks like wrong:
```
"The AcmeDemoBundle doesn't have configuration. However, the bundle is used in the configuration for the app/config/security.yml file. You can use it as a boilerplate for your own security, but you can also remove everything: it doesn't matter to Symfony if you remove it or not."
```

If I remove related with AcmeDemoBundle sections:
```
 # the login page has to be accessible for everybody
        demo_login:
            pattern:  ^/demo/secured/login$
            security: false

        # secures part of the application
        demo_secured_area:
            pattern:    ^/demo/secured/
            # it's important to notice that in this case _demo_security_check and _demo_login
            # are route names and that they are specified in the AcmeDemoBundle
            form_login:
                check_path: _demo_security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
```

I get error:
```
InvalidArgumentException in classes.php line 2639: You must at least add one authentication provider.

    in classes.php line 2639
    at AuthenticationProviderManager->__construct(array(), true) in appDevDebugProjectContainer.php line 1933
    at appDevDebugProjectContainer->getSecurity_AuthorizationCheckerService() in bootstrap.php.cache line 2097
    at Container->get('security.authorization_checker') in appDevDebugProjectContainer.php line 1949
    at appDevDebugProjectContainer->getSecurity_ContextService() in bootstrap.php.cache line 2097
    at Container->get('security.context', '2') in appDevDebugProjectContainer.php line 3086
    at appDevDebugProjectContainer->getTwigService() in bootstrap.php.cache line 2097
    at Container->get('twig') in appDevDebugProjectContainer.php line 313
    at appDevDebugProjectContainer->getAssetic_AssetManagerService() in bootstrap.php.cache line 2097
    at Container->get('assetic.asset_manager') in appDevDebugProjectContainer.php line 1899
    at appDevDebugProjectContainer->getRouting_LoaderService() in bootstrap.php.cache line 2097
    at Container->get('routing.loader') in classes.php line 1551
    at Router->getRouteCollection() in classes.php line 1339
    at Router->getMatcherDumperInstance() in classes.php line 1292
    at Router->getMatcher() in classes.php line 1269
    at Router->matchRequest(object(Request)) in classes.php line 2001
    at RouterListener->onKernelRequest(object(GetResponseEvent), 'kernel.request', object(TraceableEventDispatcher))
    at call_user_func(array(object(RouterListener), 'onKernelRequest'), object(GetResponseEvent), 'kernel.request', object(TraceableEventDispatcher)) in WrappedListener.php line 61
    at WrappedListener->__invoke(object(GetResponseEvent), 'kernel.request', object(ContainerAwareEventDispatcher))
    at call_user_func(object(WrappedListener), object(GetResponseEvent), 'kernel.request', object(ContainerAwareEventDispatcher)) in classes.php line 1790
    at EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.request', object(GetResponseEvent)) in classes.php line 1723
    at EventDispatcher->dispatch('kernel.request', object(GetResponseEvent)) in classes.php line 1884
    at ContainerAwareEventDispatcher->dispatch('kernel.request', object(GetResponseEvent)) in TraceableEventDispatcher.php line 112
    at TraceableEventDispatcher->dispatch('kernel.request', object(GetResponseEvent)) in bootstrap.php.cache line 3011
    at HttpKernel->handleRaw(object(Request), '1') in bootstrap.php.cache line 2984
    at HttpKernel->handle(object(Request), '1', true) in bootstrap.php.cache line 3133
    at ContainerAwareHttpKernel->handle(object(Request), '1', true) in bootstrap.php.cache line 2377
    at Kernel->handle(object(Request)) in app_dev.php line 28
```

I believe that phrase "but you can also remove everything: it doesn't matter to Symfony if you remove it or not."  is incorrect.

**Comment by xabbuh** [comment]
@zomberg How does your `security.yml` file look like now?

**Comment by zomberg** [comment]
```
# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        # the login page has to be accessible for everybody
#        demo_login:
#            pattern:  ^/demo/secured/login$
#            security: false
#
#        # secures part of the application
#        demo_secured_area:
#            pattern:    ^/demo/secured/
#            # it's important to notice that in this case _demo_security_check and _demo_login
#            # are route names and that they are specified in the AcmeDemoBundle
#            form_login:
#                check_path: _demo_security_check
#                login_path: _demo_login
#            logout:
#                path:   _demo_logout
#                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/cookbook/security/access_control.html
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
```
