### ISSUE TITLE
[Translation] add doc + note about how to use doctrine cache.

### ISSUE THREAD

**Issue by aitboudad** [symfony/symfony-docs#5135]
https://github.com/symfony/symfony/pull/13986

```yaml
#config.yml
framework:
    translator: { fallbacks: [en], cache: translation.cache.doctrine }

doctrine_cache:
    providers:
        translation_cache:
            memcached:
                servers:
                    localhost: 11211
```
```yaml
#services.yml
translation.cache.doctrine:
    class: Symfony\Bridge\Doctrine\Translation\DoctrineMessageCache
    arguments: [@doctrine_cache.providers.translation_cache, %kernel.debug%]
```
