### ISSUE TITLE
[2.8][Translation] specify additional translation loading paths

### ISSUE THREAD

**Issue by aitboudad** [symfony/symfony-docs#5236]
This allow to add custom resources path via prepend config or in config.yml

```yml
framework:
    translator:
        paths:
            - %kernel.root_dir%/../vendor/Symfony/Component/Form/Resources/translations
```

see https://github.com/symfony/symfony/pull/14561
