### ISSUE TITLE
[Cookbook] Obsolete example in security/target_path.html

### ISSUE THREAD

**Issue by ogizanagi** [symfony/symfony-docs#5980]
Since https://github.com/symfony/symfony/pull/14593, the example shown in ["How to Change the default Target Path Behavior"](http://symfony.com/doc/2.7/cookbook/security/target_path.html) is no longer relevant, as XHR requests are already ignored by default.

As the cookbook entry might be useful beside that detail, I think another example should be found.

Additionally, the `*.class` parameters where removed in 3.0. So you can't change the `security.exception_listener` service class as described anymore in 3.0+

```yaml
parameters:
    # ...
    security.exception_listener.class: Ap... # This parameter no longer exists in 3.0+
```

But I think it should not even be mentioned in < 3.0 docs, and always use decoration or a compiler pass instead.
