### ISSUE TITLE
Symfony3 doc Service container example

### ISSUE THREAD

**Issue by bigs21** [symfony/symfony-docs#5999]
In the documentation, at http://symfony.com/doc/3.0/book/service_container.html#creating-configuring-services-in-the-container the file to edit is not correct.

It points to config.yml:
``` yaml
# app/config/config.yml
services:
    my_mailer:
        class:        Acme\HelloBundle\Mailer
        arguments:    [sendmail]
```

But should be services.yml:
``` yaml
# app/config/services.yml
services:
    my_mailer:
        class:        Acme\HelloBundle\Mailer
        arguments:    [sendmail]
```

The same may be the case for XML and PHP formats.
