### ISSUE TITLE
Documentation for the new PSR-6 Cache component

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#6171]
- [x] symfony/symfony#17408 (the component)
- [ ] symfony/symfony#18667 (integration into the FrameworkBundle)

**Comment by javiereguiluz** [comment]
I love the energy and passion that the Symfony community is showing around the new Cache component. I'd like to start documenting it and adding it to symfony.com list of components.

---

But before that, I'd like to share with you how I'd like this new cache to work in Symfony. I'd like to have a "global" and standard way of using a cache for services and bundles. Similar to the way we use Monolog today for logging anything.

So, my question: is the following explanation how the Cache would work in Symfony?

---

### Defining application caches

When defining one cache, Symfony names it `default` automatically (same behavior as "swiftmailer" mailers and "doctrine" managers)

```yaml
# app/config/config.yml

# simple cache without arguments
cache:
    type: array

# equivalent to:
# cache:
#    default:
#        type: array
```

Complex caches can define arguments:

```yaml
# app/config/config.yml
cache:
    type: doctrine
    em: my_custom_em_id
```

You can also define lots of different caches in a single app:

```yaml
# app/config/config.yml
cache:
    default:
        type: array
    db:
        type: doctrine
        em: my_custom_em_id
```

They are available in the application as `cache.default` and `cache.db` services.
The `cache` service is an alias for `cache.default`.

### Configuring the application caches

Params such as `default_lifetime` and `namespace` are available for any cache type:

```yaml
# app/config/config.yml
cache:
    type: array
    default_lifetime: 600
    namespace: 'ACME__'
```

### Using caches in Symfony components

All Symfony components define a `cache` option. Its value can be:

1) A boolean, to enable or disable the cache. If `true`, the `default` cache is used:

```yaml
# app/config/config.yml
framework:
    validation:
        cache: true
        enable_annotations: true
    serializer:
        cache: true
    property_path:
        cache: true

doctrine:
    orm:
        cache: true
# you can also set 'metadata_cache_driver', 'result_cache_driver' 
# and 'query_cache_driver' separately
```

You can also set the `id` of the cache and even an array of cache ids for complex services:

```yaml
# app/config/config.yml
framework:
    validation:
        cache: db
        enable_annotations: true
    serializer:
        cache: default
    property_path:
        cache: default

doctrine:
    orm:
        cache: [db, default]
```

This cache can also be used for third-party bundles:

```yaml
# app/config/config.yml
liip_imagine:
    cache: true # or false, or 'db', or ['db', 'default'], etc.
```

**Comment by WouterJ** [comment]
What you are mentioning is not Component docs, but bundle docs (cookbook related), @javiereguiluz.

Apart from that, I cannot answer your questions as I haven't looked at caching yet

**Comment by xabbuh** [comment]
@javiereguiluz Your ideas sound quite nice to me and I think you should raise this idea in the code repo (we are not there right now, but the work to integrate PSR-6 caches in the different components has started). Some of the things you talk about are out of the scope of the Symfony core as they need to be handled in third-party bundles, but we should of course think about how can make using the new cache component as easy as possible.

**Comment by xabbuh** [comment]
For anyone interested: Javier opened symfony/symfony#17537.

**Comment by teohhanhui** [comment]
Is there any documentation for #18371 (also #18544 and #18561 which introduced default cache pools for the Validator and Serializer)?

How would the user switch to use `ApcuAdapter`, for instance? Is it by overriding the adapter for the default cache pools, or by declaring new cache pools?

`validator.mapping.cache.doctrine.apc` and `serializer.mapping.cache.doctrine.apc` are using the old `ApcCache` which requires the `apcu_bc` PECL package (`apc.so` extension) for PHP >= 7.

**Comment by tgalopin** [comment]
@teohhanhui You are right, these PR should be documented.

However, note that these three PR do not change any behavior when the user enabled APC cache: these PR are simply a fallback to filesystem when the user didn't change the config_prod file.

The recommended cache will also need to change from APC to OPCache as much as possible. That's the aim of the PR https://github.com/symfony/symfony/pull/18533 and there will be other PRs for other components (validator and serializer mainly).

**Comment by tgalopin** [comment]
This comment could be a good basis for documentation: https://github.com/symfony/symfony/pull/18371#issuecomment-204300288

**Comment by teohhanhui** [comment]
An educated guess from the code says that I can safely do this:

```yaml
# app/config.yml
framework:
    cache:
        pools:
            serializer:
                adapter: cache.adapter.apcu
```

Am I right?

https://github.com/symfony/symfony/blob/db208e3e25c9e80c6f0d73a59253037812582ac5/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1025-L1032

and

https://github.com/symfony/symfony/blob/4f0b8beea6bbbe9c60fa8189e0e7b9443bcc8ea7/src/Symfony/Bundle/FrameworkBundle/Resources/config/cache_pools.xml#L28-L30
