### ISSUE TITLE
[MonologBundle] New use_microseconds param

### ISSUE THREAD

**Issue by Seldaek** [symfony/symfony-docs#6466]
http://symfony.com/doc/current/cookbook/logging/monolog.html#usage should maybe mention the new use_microseconds parameter that was added in 2.11 (https://github.com/symfony/monolog-bundle/releases/tag/2.11.0).

It lets you disable microsecond precision, which speeds up log generation a tiny bit. It's kind of a micro optimization but if you log a lot of debug messages it can matter.

```yaml
monolog:
    use_microseconds: false
    handlers: ...
```
