### ISSUE TITLE
Symfony 3.0 Inject Container in FormType

### ISSUE THREAD

**Issue by zhaocunyang** [symfony/symfony-docs#6558]
I according to the wording of the official website [defining-your-forms-as-services](http://symfony.com/doc/current/book/forms.html#defining-your-forms-as-services)

```yaml
service:
   app.form.type.content:
        class: App\AdminBundle\Form\ContentType
        arguments: [ '@service_container' ]
        tags:
            - { name: form.type }
```

formType:

```php
     private $container;
    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
    }
```

then have a error:

```
Catchable Fatal Error: Argument 1 passed to App\AdminBundle\Form\ContentType::__construct() must implement interface Symfony\Component\DependencyInjection\ContainerInterface, none given, called in /vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php on line 85 and defined
```
