### ISSUE TITLE
[Workflow] Add documentation for the Workflow Component

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony-docs#6677]
Hi!

https://github.com/symfony/symfony/pull/11882 is finally merged.
So the next step is to document this component + the integration into the FrameworkBundle.

But I'm really not good enough to achieve this task BUT I'm 100% available for helping anyone with that.
I created this [little app](https://github.com/lyrixx/SFLive-Paris2016-Workflow) to show how it works in action and there is also this [french presentation](https://speakerdeck.com/lyrixx/le-reveil-du-workflow).

**Comment by Nyholm** [comment]
I can have a look at this at the beginning of August. If anyone is interested to start before that just write on this issue. 

I will write a comment when I actually begin.

**Comment by Nyholm** [comment]
I've started on a PR now

**Comment by xabbuh** [comment]
#6871 is merged now. However, there is some late feedback we may want to talk about. That's why I decided not to close here.

**Comment by rmasclef** [comment]
Hi !

I noticed that there is no documentation about the the behavior of the workflow component when we do not set a `marking_store`.

When we take a look at @lyrixx demo (https://github.com/lyrixx/SFLive-Paris2016-Workflow), we can see that he do not set the `type` and the `marking_store` in its configuration. But there is a `marking` property in the `supports` object ...

Perhaps it will be good to add these default values in the doc ?

I noticed another thing concerning the behavior of the workflow component with the `supports` object:

If we take a look at this example:

### config.yml
```
framework:
    workflows:
        request_for_operation:
            type: 'state_machine'
            marking_store:
                type: 'single_state'
                arguments:
                    - 'status'
            supports:
                - AppBundle\Entity\RequestForOperation
            places:
                - draft
                - pending_for_management
                - in_progress
                - finished
                - canceled
            transitions:
                save:
                    from: draft
                    to:   pending_for_management
                track:
                    from: pending_for_management
                    to:   in_progress
                close:
                    from: in_progress
                    to:   finished
                cancel:
                    from: [pending_for_management, in_progress]
                    to:   canceled
```

### RequestForOperation.php
```
class RequestForOperation
{
    /**
     * @ORM\Column(name="status", type="string", nullable=true)
     */
    private $status;
    
    ...
}
```
The initial place seems to be `draft`.

On a RequestForOperation creation, is the `status` automatically set to `draft` ? or is this `draft` place not really "existing" (i.e status = null) ?
