### ISSUE TITLE
Services can now define default options per file

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7339]
Example:

```yaml
services:
    _defaults:
        public: false
        autowire: ['_construct', 'set*']

    foo:
        class: Foo
```

See https://github.com/symfony/symfony/pull/21071
