### ISSUE TITLE
[FrameworkBundle] Files can now be referenced directly from kernel.root_dir

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7369]
See https://github.com/symfony/symfony/pull/21231

You can now do things like this:

```yaml
app:
    resource: "../src/Controller/"
    type: annotation
```
