### ISSUE TITLE
Document the new short Yaml syntax for service definition

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7441]
Added in https://github.com/symfony/symfony/pull/21313

Before:

```yaml
services:
    App\Foo\Bar: 
        arguments: ['@baz', 'foo', '%qux%']
```

After:

```yaml
services:
    App\Foo\Bar: ['@baz', 'foo', '%qux%']
```
