### ISSUE TITLE
Help with validation array via yaml mapping

### ISSUE THREAD

**Issue by alexpts** [symfony/symfony-docs#7648]
I try validate assoc array via symfony validation.

I could validate array in php notation:

```php
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Validation;

$constraint = new Collection([
    'fields' => [
        'email' => new Email(),
        'person' => new Optional(new Email())
    ]
]);

$validator = Validation::createValidatorBuilder()->getValidator();

$errors = $validator->validate(['email' => 'email', 'name' => null], $constraint);
```

I want use yaml definition rule.

```yml
# validation.yml
Collection:
    name:
      - NotBlank
      - Length:
          min: 2
    email:
      - Email
```
```php
$validator = Validation::createValidatorBuilder()
    ->addYamlMapping('validation.yml')
    ->getValidator();

$errors = $validator->validate(['email' => 'email', 'name' => null]);
```

Can someone help me check an assoc array with a description of the rules through yaml?

In the documentation, very little is described about working with arrays.

**Comment by HeahDude** [comment]
Hello @alexpts, the documentation of the Collection contraint looks pretty explicit to me in all format, I've only spotted a typo while checking it (see #7686).

To use yaml definition, you should use something like:
```yaml
ClassName:
    properties:
        someArrayPropertyName:
            - Collection:
                fields:
                    name:
                        - NotBlank
                        - Length: { min: 2 } } }
                    email:
                        - Email
```

Your problem may come from the absence of model data to validate though, this is not needed in full PHP, but using yaml you cannot just define a constraint, you need to map a class and class properties to constraints. It means a simple PHP array cannot have mapped constraint through yml or xml.

Anyway I'm closing here, feel free to ask your question through one of our [dedicated support channel](http://symfony.com/support).
