### ISSUE TITLE
Test Http Authentication

### ISSUE THREAD

**Issue by lecneri** [symfony/symfony-docs#8005]
Hi,

The docs in http://symfony.com/doc/current/testing/http_authentication.html 
says too add the following content to config_test.yml
``` 
security:
    firewalls:
        your_firewall_name:
            http_basic: ~
```

Although when you do that and try to test you run into this error:

> Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: You are not allowed to define new elements for path "security.firewalls". Please define all elements for this path in one config file.

This is because config.yml imports security.yml that already has security.firewalls defined.
Btw, anyone know a good way to make this http authentication test work?
