### ISSUE TITLE
guard_authentication documentation for api firewall

### ISSUE THREAD

**Issue by hackzilla** [symfony/symfony-docs#8051]
I can't figure out how `your_db_provider` property apiKey is actually used with $userProvider->loadUserByUsername($apiKey); 

```yaml
# app/config/security.yml
security:
    # ...

    providers:
        your_db_provider:
            entity:
                class: AppBundle:User
                property: apiKey

    # ...
```
near https://symfony.com/doc/current/security/guard_authentication.html#create-a-user-and-a-user-provider

There is no mention of modifying UserRepository-> loadUserByUsername to handle apiKey.

```php
    public function getUser($credentials, UserProviderInterface $userProvider)
    {
        $apiKey = $credentials['token'];

        if (null === $apiKey) {
            return;
        }

        // if null, authentication will fail
        // if a User object, checkCredentials() is called
        return $userProvider->loadUserByUsername($apiKey);
    }
```

I was expecting the property key to be passed somehow into ```UserLoaderInterface```
```yaml
property: apiKey
```

My current expectation is to create another method ```loadUserByApiKey```
