### ISSUE TITLE
Better explain how autowiring works in some cases

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8372]
Given this config:

```yaml
services:
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: [controller.service_arguments]

    AppBundle\Controller\AdminController:
        arguments:
            $adminEmail: 'manager@example.com'
```

One may think that `AdminController` is public and has the `controller.service_arguments` tag ... but it doesn't.

Defining services in bulk (such as the typical `App\Controller\` import) is not the same as defining default options for those services (you need to use `_defaults` for that).

So, in this case, the `AdminController` is first automatically configured by the `AppBundle\Controller\:` config ... and then overridden by the `AppBundle\Controller\AdminController` config, so you lose everything: ` public`, `tags`, etc.
