### ISSUE TITLE
Importing Many Services at once with resource - kernel.project_dir vs relative path

### ISSUE THREAD

**Issue by LPodolski** [symfony/symfony-docs#8373]
I don't really understand why in doc is recommended to use relative path `../../` instead of using parameter like: %kernel.project_dir%

It's used in many blog posts and docs like for example
```yaml
    AppBundle\:
        # accepts a glob pattern
        resource: '../../src/AppBundle/*'
        # exclude some paths
        exclude: '../../src/AppBundle/{Entity,Repository}'
```

Is there a reason why not using: `resource: '%kernel.project_dir%/src/AppBundle/*'` ?

It's puzzling for me because in most other places parameters are used instead or relative path navigation like:

https://symfony.com/doc/current/configuration.html
`router:          { resource: '%kernel.project_dir%/app/config/routing.yml' }`

where working option would be also:
`router:          { resource: '../../app/config/routing.yml' }`

or even simpler:
`router:          { resource: './routing.yml' }`

and I wonder if there is any reason for beeing inconsistent like that

https://symfony.com/doc/current/service_container.html#service-psr4-loader

https://github.com/symfony/symfony-docs/blob/master/service_container.rst#creatingconfiguring-services-in-the-container
