### ISSUE TITLE
[DependencyInjection] Allow dumping inline services in YAML

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8381]
See https://github.com/symfony/symfony/pull/23855 and the example in the fixtures:

```yaml
services:
    service_container:
        class: Symfony\Component\DependencyInjection\ContainerInterface
        synthetic: true
    foo:
        class: Class1
        arguments: [!service { class: Class2, arguments: [!service { class: Class2 }] }]
    Psr\Container\ContainerInterface:
        alias: service_container
        public: false
    Symfony\Component\DependencyInjection\ContainerInterface:
        alias: service_container
        public: false
```
