### ISSUE TITLE
Update docs about class named services

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony-docs#8403]
E.g. https://symfony.com/doc/current/service_container/tags.html

Talks about

```yaml
    Swift_SmtpTransport:
        arguments: ['%mailer_host%']
        tags:
            - { name: app.mail_transport, alias: smtp }

# ...
    Swift_SendmailTransport:
        class: \Swift_SendmailTransport
        tags: [app.mail_transport]
```

The first-like variants wont work, and i also think we should avoid leading `\` in class attr. This might break any normalization check. Standard is no leading slash.

See also https://github.com/symfony/symfony/pull/24145

basically using poor-man namespacing by example makes your life hard.
