### ISSUE TITLE
Usage of non-existing cache provider services

### ISSUE THREAD

**Issue by aik099** [symfony/symfony-docs#8406]
On the https://symfony.com/doc/current/reference/configuration/framework.html page, when cache providers are listed (close to the bottom) each has associated service shown:

* `cache.doctrine`
* `cache.redis`

and others. I wasn't able to find a place where these services are registered and `$this->get(...)` is throwing non-existing service exception when attempting to get them.

Maybe `cache.redis` (in docs) should be replaced with `cache.adapter.redis` and so on.

**Comment by xabbuh** [comment]
Actually, these alias are registered, but they are private (see 
https://github.com/symfony/symfony/blob/3.3/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1425-L1429). Thus, *if*  you wanted to use them yourself, you would have to inject them instead of using the container as a service locater (or register a public alias yourself). I just wonder how useful it actually is for the end user to know these internal services names.

@nicolas-grekas What do you think?

**Comment by nicolas-grekas** [comment]
The doc is inaccurate: there is no cache.redis/cache.psr6 pools.
The `default_*_provider` are applicable to any *user defined* pool only. If there are none, the setting is useless.

Here is an example:
```yaml
  cache:
    default_redis_provider: redis://...
    pools:
      my_pool1: {adapter: cache.adapter.redis}
      my_pool2: {adapter: cache.adapter.redis, provider: "redis://..."} # same as previous, explicit provider
```
The main use case is configuring the default app storage:

```yaml
  cache:
    app: cache.adapter.redis
    default_redis_provider: redis://...
    pools:
      my_pool1: ~
      my_pool2: ~
```
defines two pools (in addition to the generic `cache.app` one with separate namespace, but same redis storage.
