### ISSUE TITLE
Document how to set session.cache_limiter

### ISSUE THREAD

**Issue by goetas** [symfony/symfony-docs#8784]
The current session implementation sends some "Cache" headers really similar to http://php.net/manual/en/function.session-cache-limiter.php

This behavior can be configured by  setting some properties into the parameter, `session.storage.options`

As example:

```yaml
# config/packages/framework.yaml
parameters:
    session.storage.options:
        cache_limiter: 0
```

If `cache_limiter` is `0` symfony will not set any particular header header and will fallback on what specified by http://php.net/manual/en/session.configuration.php#ini.session.cache-limiter

`cache_limiter` can also be set to one of the nocache, private, private_no_expire, or public vales 

Related to https://github.com/symfony/symfony/issues/24988#issuecomment-348144008

As suggested here https://github.com/symfony/symfony/issues/24988#issuecomment-348144790 should be documented that changing this value should be done carefully.
