### ISSUE TITLE
correct settings for gmail

### ISSUE THREAD

**Issue by gonzakpo** [symfony/symfony-docs#8937]
```yaml
# app/config/config_dev.yml
swiftmailer:
    transport: gmail
    username:  your_gmail_username
    password:  your_gmail_password
    stream_options:
        ssl:
            verify_peer:  false
            verify_peer_name: false
```

**Comment by javiereguiluz** [comment]
This disables any SSL verification, right? I don't think that's a solution we want to promote. Can you please show us which error do you see in the app? Also, please check this --> https://symfony.com/doc/current/email.html#using-gmail-to-send-emails (the config format will be different if you don't use Symfony 4.0 yet).

**Comment by gonzakpo** [comment]
Symfony 3.1
probe many configurations, says sent but the mail never arrives.
Invalid configuration for path "swiftmailer.mailers.default.auth_mode": The "oauth" authentication mode is not supported

**Comment by javiereguiluz** [comment]
This works for me in an old Symfony app:

```
parameters:
    mailer_transport: smtp
    mailer_host: smtp.gmail.com
    mailer_port: 465
    mailer_encryption: ssl
    mailer_auth_mode: login
    mailer_user: '___________@gmail.com'
    mailer_password: '●●●●●●●●●●●●'
```
