### ISSUE TITLE
[Routing] Allow to set name prefixes from the configuration

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9020]
Similar to `prefix` but it allows to add a prefix to the name of some routes:

```yaml
api:
    resource: ../controller/routing.yml
    name_prefix: api_
    prefix: /api
```

https://github.com/symfony/symfony/pull/25178
