### ISSUE TITLE
wrong versions for DoctrineFixturesBundle documentation

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#9146]
It looks like the version switcher for the [DoctrineFixturesBundle docs](http://symfony.com/doc/current/bundles/DoctrineFixturesBundle/index.html) does not work as expected. As far as I can see the parts related to services have only been added by Ryan in version 3.

ping @javiereguiluz @weaverryan

**Comment by javiereguiluz** [comment]
To fix this I need to update some config file on symfony.com. This is what I've done ... but I have doubts about the values of `branches`, `maintained_branches` and `master_alias`:

```yaml
doctrine-fixtures-bundle:
    title: "Doctrine Fixtures Bundle"
    url: "https://github.com/doctrine/DoctrineFixturesBundle"
    branches: ["2.0", "3.0", "master"]
    maintained_branches: ["3.0", "master"]
    remote_prefix: "Resources/doc/"
    master_alias: "4.0"
```

Can anyone with experience in the DoctrineFixturesBundle repo help us? Thanks!

**Comment by alcaeus** [comment]
Hi! As with most other Doctrine repos, the following applies for DoctrineFixturesBundle:
* Current stable version (3.0) is supported with bugfixes
* Oldstable will receive critical security fixes, but no bugfixes
* Anything older than that is not supported.

In the case of DoctrineFixturesBundle, the 2.0 branch is outdated (I'll try to push the last 2.x release to that branch) while the 3.0 branch was a work in progress branch that has been abandoned. I haven't gotten around to cleaning it up yet.

I would suggest this config for the bundle:

```
doctrine-fixtures-bundle:
    title: "Doctrine Fixtures Bundle"
    url: "https://github.com/doctrine/DoctrineFixturesBundle"
    branches: ["master"]
    maintained_branches: ["master"]
    remote_prefix: "Resources/doc/"
    master_alias: "3.0"
```
