### ISSUE TITLE
[Security] Use constants for roles

### ISSUE THREAD

**Issue by jaikdean** [symfony/symfony-docs#9673]
The examples in the documentation currently use strings for role names. For example, [How to Use Voters to Check User Permissions](https://symfony.com/doc/current/security/voters.html) has the line:

```php
if ($this->decisionManager->decide($token, array('ROLE_SUPER_ADMIN'))) {
```

This is prone to typos, whereas using constants for roles allows IDEs and CI tools to aid in debugging, and for errors to be thrown when a constant is typed incorrectly, rather than authorization failing with an incorrectly typed string.

In another example on the same page of the documentation, constants are used to check “view” and “edit” permissions on an object.

I suggest we're consistent and encourage use of constants for roles too, as a best practice.

**Comment by alexislefebvre** [comment]
Strings are used in YAML files too: https://symfony.com/doc/2.8/security.html#b-configuring-how-users-are-loaded

Is it possible to use constants instead of strings? Could you please provide an example?

I'm wondering if this idea is related to the documentation or is a Symfony feature request.

**Comment by jaikdean** [comment]
Since Symfony 3.2 we can [use PHP constants in YAML files](https://symfony.com/blog/new-in-symfony-3-2-php-constants-in-yaml-files).

An example for the current version of the page you linked to would be something like:

```yaml
# config/packages/security.yaml
security:
    # ...
    firewalls:
        # ...
        main:
            # ...

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: !php/const App\Kernel::ROLE_ADMIN }
```

What I'm not sure of is where we should recommend defining the role constants. I've gone with `App\Kernel` above, but that's probably not the best place.
