### ISSUE TITLE
Document the integration of the Lock component in the FrameworkBundle

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony-docs#9779]
I see there is an integration between the Lock component and the FrameworkBundle,
But I can find this documentation.  I found this [doc](https://symfony.com/doc/current/components/lock.html) but it's only about the component alone.

It could be nice to get this doc ;)

Thanks

**Comment by javiereguiluz** [comment]
In 4.2 there's a new option related to this for `flock`. See https://github.com/symfony/symfony/pull/26923

**Comment by jderusse** [comment]
When I write the original `Lock` documentation draft, I only write the `Component` part, because to be honest, I didn't find out where is the "FrameworkBundle" documentation. 
We only documents options of framework's configuration (https://symfony.com/doc/3.4/reference/configuration/framework.html#lock) , and given lock's configuration contains only 1 option, this is not usefull at all.

At the time, we gave sample of configuration in the `Full Default Configuration` but this section as been removed
```
            # lock configuration
            lock:
                invoice: 'redis://localhost'
                report: semaphore
            # lock: ~
            # lock: 'flock'
            # lock: ['semaphore', 'redis://localhost']
``` 

I didn't want to invent a new thing, but at the time, I would have like to write something with:
 - a sample of configuration (the simplest way to configure the component) 
 - a (or several) sample of advanced configurations
 - how to inject it in my services (list of public aliases, and serviceId and how to use theme)

Any idea where should we put theme?

To be honest, I have the same issue with cache component. I never use framework bundle to create cacheItemPull (I configure theme in the DIC), because I never figured out how to customize theme (defining a namespace, or don't use serialization in ArrayCache) or create advanced Pools (like ChainPool) ;-)
