### ISSUE TITLE
Unclear caching documentation: pool namespaces

### ISSUE THREAD

**Issue by luispabon** [symfony/symfony-docs#9851]
The current docs for caching seem to concentrate on the cache component in isolation, with very few hints of how it actually integrates when running on the wider framework. 

In fact, I had to pick up the required framework config (see below) off a [random blog post on the internet](https://medium.com/@ScullWM/use-symfony-app-cache-as-a-service-da4b4654e2f0).

Specifically, it looks as if cache pools are given a namespace for cache keys by default. This is fine, but there's no information at all on where this namespace string is actually coming from, whether it's random or deterministic, and how (if at all possible) to configure it. 

As a developer, I'm usure of what will happen when I deploy my app as I do not have information to know whether several deployed instances of my app will be using the same namespace.

```
parameters:
    redis_dsn: "redis://%env(REDIS_HOST)%"

framework:
    [...]
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%redis_dsn%'
```
