### ISSUE TITLE
[messenger] 

### ISSUE THREAD

**Issue by CuiKeng** [symfony/symfony-docs#9960]
# config/packages/messenger.yaml
framework:
    messenger:
        routing:
            'My\Message\ThatIsGoingToBeSentAndHandledLocally': [amqp, ~]

Not work for null, trigger an exception:
Invalid type for path "framework.messenger.routing.App\Command\CreateBugCommand.senders". Expected array, but got string

**Comment by HeahDude** [comment]
Thanks @CuiKeng for the report. (Note that by enclosing your code with ``` you can format it to ease readability, I've edited your description to add those)

**Comment by javiereguiluz** [comment]
Friendly ping to Messenger experts @ogizanagi and @sroze. Thanks!

**Comment by ogizanagi** [comment]
Hello 👋 

Documentation was actually fixed in #10473 . `send_and_handle` must be used instead of a `null` sender.

```yml
framework:
    messenger:
        routing:
            'My\Message\ThatIsGoingToBeSentAndHandledLocally':
                 senders: [amqp]
                 send_and_handle: true
```

- https://symfony.com/doc/current/messenger.html#routing
